name: catalog_website
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.2.1
  widgetbook: ^3.16.0
  widgetbook_annotation: ^3.7.0
  feather_core: any
  feather_ui: any
  google_fonts: ^6.3.1
  get_it: ^8.2.0
  path_provider: ^2.1.5
  path: ^1.9.1
  device_preview: ^1.3.1
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  url_launcher: ^6.3.2
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.26.3
  flutter_lints: ^6.0.0
  build_runner: ^2.9.0
  riverpod_generator: ^3.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/