name: catalog_website
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  go_router: ^16.2.1
  widgetbook: ^3.16.0
  widgetbook_annotation: ^3.7.0
  feather_core:
    path: ../feather_core
  feather_ui:
    path: ../feather_ui
  sidebarx: ^0.17.2
  google_fonts: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/