name: feather

environment:
  sdk: ^3.8.0

workspace:
  - packages/feather_generator
  - packages/feather_ui
  - packages/catalog_website
  - packages/feather_registry
  - packages/feather_core
  - packages/feather_cli

dev_dependencies:
  build_runner: ^2.8.0
  melos: ^7.1.1

melos:
  scripts:
    generate:
      run: melos exec -c 1 --depends-on build_runner -- dart run build_runner build
    update_widgets:
      run: |
        cd packages/feather_ui
        dart run build_runner build --delete-conflicting-outputs
        echo "Copying generated files..."
      
        #feather_registry
        mkdir -p ../feather_registry/lib/_generated
        cp lib/_generated/*.g.json ../feather_registry/lib/_generated/
      
        #catalog_website
        mkdir -p ../catalog_website/lib/_generated
        cp lib/_generated/*.g.dart ../catalog_website/lib/_generated/
  
    format:
      run: melos exec -- dart format .

    pre-commit:
      description: pre-commit git hook script
      steps:
        - format --output none --set-exit-if-changed
        #- dart test --fail-fast .
