name: feather_generator
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0

resolution: workspace

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^9.0.0
  
dependencies:
  analyzer: ^8.1.1
  build: ^4.0.0
  change_case: ^2.2.0
  feather_core: any
  glob: ^2.1.3
  source_gen: ^4.0.1