name: feather_core
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/AbhijithKonnayil/feather/tree/main/packages/feather_core

environment:
  sdk: ^3.8.0
  
resolution: workspace

# Add regular dependencies here.
dependencies:
  yaml: ^3.1.3
  mason_logger: ^0.3.3
  json_annotation: ^4.9.0

dev_dependencies:
  json_serializable: ^6.11.1
  lints: ^6.0.0
  test: ^1.26.3
