name: feather_core
description: Core infrastructure and shared utilities powering the Feather Design System
version: 0.0.1-dev.2
repository: https://github.com/AbhijithKonnayil/feather/tree/main/packages/feather_core
homepage: https://feather.aioncw.com/

environment:
  sdk: ^3.8.0
  
resolution: workspace

# Add regular dependencies here.
dependencies:
  yaml: ^3.1.3
  json_annotation: ^4.9.0
  logger: ^2.6.2
  mason_logger: ^0.3.3

dev_dependencies:
  json_serializable: ^6.11.1
  lints: ^6.0.0
  test: ^1.26.3
