blank_issues_enabled: false
contact_links:
  - name: Feather documentation
    url: https://github.com/AbhijithKonnayil/feather/#README.md
    about: Read the README and docs for setup, usage, and FAQs.

