name: feather_ui
description: A Very Good Project created by Very Good CLI.
version: 0.0.1
repository: https://github.com/AbhijithKonnayil/feather/tree/main/packages/feather_ui

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  feather_core: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
  build_runner: ^2.8.0
  feather_generator:
    path:
      ../feather_generator
