name: feather_cli
description: A command-line interface for the Feather UI framework, providing tools for widget development, code generation, and project management.
version: 0.0.1-dev.2
repository: https://github.com/AbhijithKonnayil/feather/tree/main/packages/feather_cli

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  args: ^2.7.0
  change_case: ^2.2.0
  cli_completion: ^0.5.1
  #TODO Remove logger and user from core
  feather_core: ^0.0.1-dev.4
  pub_updater: ^0.5.0

dev_dependencies:
  build_runner: ^2.6.0
  build_verify: ^3.1.1
  build_version: ^2.1.2
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
  test: ^1.26.3

dependency_overrides:
  test: ^1.26.3
  test_api: 0.7.6
executables:
  feather_cli:
