name: feather_registry
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/AbhijithKonnayil/feather/tree/main/packages/feather_registry

environment:
  sdk: ^3.9.0

resolution: workspace

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
